# For more details, see https://docs.github.com/en/actions
name: Build and push docker image

# Controls when the workflow will run
on: [workflow_dispatch]

# For more details, see https://docs.github.com/en/actions/using-workflows/reusing-workflows
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zhuoqiw/ros-pylon:latest
            zhuoqiw/ros-pylon:7.3.0
